variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build-GCC
  - build-Clang
  - demo
  - quality
  - deploy

include:
  - "/.gitlab/ci/build-baremetal.yml"
  - "/.gitlab/ci/build-linux.yml"
  - "/.gitlab/ci/demo-baremetal.yml"
  - "/.gitlab/ci/demo-linux.yml"
  - "/.gitlab/ci/deploy.yml"
  - "/.gitlab/ci/quality.yml"
