variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build-GCC
  - build-Clang
  - demo
  - quality
  - deploy

include:
  - ".gitlab/ci/build-demo-baremetal.yml"
#  - ".gitlab/ci/build-demo-linux.yml"
#  - ".gitlab/ci/deploy.yml"
#  - ".gitlab/ci/quality.yml"
  - ".gitlab/ci/run-demo-baremetal.yml"
#  - ".gitlab/ci/run-demo-linux.yml"
