name: Collect coverage data for binary
description: Collect coverage data for binary

inputs:
  preset:
    description: CMake preset used to build the binary
    required: true

  artifactSuffix:
    description: Suffix appended to the artifact name
    required: false

  binary:
    description: Binary to run
    required: true

  coverage-include-pattern:
    description: Pattern for lcov --extract to filter coverage (e.g., "lib")
    required: false
    default: lib
  gcov-prefix-strip:
    description: Value for GCOV_PREFIX_STRIP environment variable
    required: false
    default: 3
  run-args:
    description: Command line arguments to pass to the binary
    required: false
  run-env:
    description: Additional environment variables for the binary (multiline string)
    required: false
  lcov-branch-coverage:
    description: Enable branch coverage in lcov (true/false)
    required: false
    default: true

outputs:
  coverage-file:
    description: Name of the generated coverage info file
    value: ${{ steps.set-outputs.outputs.coverage-file }}
  artifact-name:
    description: Name of the uploaded coverage artifact
    value: ${{ steps.set-outputs.outputs.artifact-name }}

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v6
      with:
        name: coverage-build-${{ inputs.preset }}${{ inputs.artifactSuffix }}
        path: coverage-artifacts/

    - name: Setup test environment
      shell: bash
      run: |
        echo "=== Downloaded artifacts ==="
        find coverage-artifacts || echo "No artifacts found"

        # Create working directory for this test
        mkdir -p test-${{ inputs.binary }}
        cd ${{ inputs.binary }}

        # Copy the specific binary
        cp ../coverage-artifacts/bin/${{ inputs.binary }} .

        # Copy gcno files while preserving directory structure
        # Note: gcov requires exact path matching between gcno and gcda files
        if [ -d "../coverage-artifacts/gcno" ]; then
          echo "Found gcno directory, copying..."
          # Copy the entire directory structure
          cp -r ../coverage-artifacts/gcno/* ./ 2>/dev/null || true

          # Also create the required directory structure for gcda files
          # Based on our POC, we need the full build path structure
          find ../coverage-artifacts/gcno -type d -exec mkdir -p {} \; 2>/dev/null || true
        else
          echo "WARNING: No gcno directory found in artifacts!"
          echo "Looking for gcno files in other locations..."
          find ../coverage-artifacts -name "*.gcno" || echo "No gcno files found anywhere"
        fi

        # Make binary executable
        chmod +x ${{ inputs.binary }}

        # Debug: List what we have set up
        echo "=== Test environment setup for ${{ inputs.binary }} ==="
        echo "Binary:"
        ls -la ${{ inputs.binary }}
        echo "Total gcno files: $(find . -name "*.gcno" | wc -l)"
        echo "Directory structure:"
        find . -type d | head -10
        echo "Sample gcno files:"
        find . -name "*.gcno" | head -5

    - name: Run binary and collect coverage data
      shell: bash
      run: |
        cd test-${{ inputs.binary }}

        # Check what paths are embedded in the gcno files
        echo "=== Sample embedded paths in gcno files ==="
        find . -name "*.gcno" -exec strings {} \; | grep "^/" | head -10 || echo "No absolute paths found in gcno files"

        # Verify we have the expected directory structure
        echo "=== Verifying directory structure ==="
        echo "Looking for build/ directory:"
        ls -la build/ 2>/dev/null || echo "No build/ directory found"
        echo "Sample gcno file paths:"
        find . -name "*.gcno" | head -3

        # Set GCOV environment variables for coverage data generation
        # GCOV_PREFIX: Base directory where gcda files will be written
        # GCOV_PREFIX_STRIP: Number of path components to strip from embedded paths
        export GCOV_PREFIX="$PWD"
        export GCOV_PREFIX_STRIP=${{ inputs.gcov-prefix-strip }}

        echo "GCOV_PREFIX: $GCOV_PREFIX"
        echo "GCOV_PREFIX_STRIP: $GCOV_PREFIX_STRIP"

        # Apply additional environment variables if provided
        if [ -n "${{ inputs.run-env }}" ]; then
          echo "=== Applying additional environment variables ==="
          echo "${{ inputs.run-env }}" | while IFS= read -r line; do
            if [ -n "$line" ]; then
              export "$line"
              echo "Set: $line"
            fi
          done
        fi

        # Run the binary
        echo "Running ${{ inputs.binary }}..."
        ./${{ inputs.binary }} ${{ inputs.run-args }} || {
          echo "ERROR: Binary execution failed"
          exit 1
        }

        # Check for generated gcda files
        echo "=== Generated gcda files ==="
        gcda_files=$(find . -name "*.gcda" -type f)
        if [ -n "$gcda_files" ]; then
          echo "$gcda_files"
        fi
        gcda_count=$(echo "$gcda_files" | grep -c "." || echo "0")
        echo "Total: $gcda_count files"

        # If no gcda files found, this is a problem
        if [ "$gcda_count" -eq 0 ]; then
          echo "ERROR: No gcda files generated!"
          echo "This indicates coverage instrumentation is not working properly"
          echo "Checking available gcno files:"
          find . -name "*.gcno" -type f
          echo "Trying to run binary with different GCOV settings..."

          # Try without GCOV_PREFIX to see if gcda files appear in original locations
          unset GCOV_PREFIX
          unset GCOV_PREFIX_STRIP
          echo "Running without GCOV environment variables..."
          ./${{ inputs.binary }} ${{ inputs.run-args }}

          echo "Checking for gcda files anywhere after second run:"
          find . -name "*.gcda" -type f

          if [ $(find . -name "*.gcda" -type f | wc -l) -eq 0 ]; then
            echo "FATAL: Still no gcda files - coverage is broken"
            exit 1
          fi
        fi

    - name: Generate filtered coverage info
      shell: bash
      run: |
        cd test-${{ inputs.binary }}

        # Check if we have both gcno and gcda files
        gcno_count=$(find . -name "*.gcno" -type f | wc -l)
        gcda_count=$(find . -name "*.gcda" -type f | wc -l)

        echo "Found $gcno_count gcno files and $gcda_count gcda files"

        if [ "$gcda_count" -eq 0 ]; then
          echo "ERROR: No gcda files found - coverage data was not generated"
          echo "This usually means the binary didn't run with coverage enabled"
          echo "Gcno files present:"
          find . -name "*.gcno" -type f
          exit 1
        fi

        # Generate coverage info from all gcda files
        echo "Generating coverage info with lcov..."
        if [ "${{ inputs.lcov-branch-coverage }}" = "true" ]; then
          lcov --capture --directory . --output-file ${{ inputs.binary }}-all.info --gcov-tool gcov --rc lcov_branch_coverage=1 || {
            echo "Error: lcov capture with branch coverage failed."
            echo "Trying without branch coverage..."

            # Try without branch coverage
            lcov --capture --directory . --output-file ${{ inputs.binary }}-all.info --gcov-tool gcov || {
              echo "Error: lcov capture failed completely. Debug info:"
              echo "Gcda files:"
              find . -name "*.gcda" -type f
              echo "Gcno files:"
              find . -name "*.gcno" -type f
              echo "Working directory:"
              pwd
              echo "Directory structure:"
              find . -type f | head -20
              exit 1
            }
          }
        else
          lcov --capture --directory . --output-file ${{ inputs.binary }}-all.info --gcov-tool gcov || {
            echo "Error: lcov capture failed. Debug info:"
            echo "Gcda files:"
            find . -name "*.gcda" -type f
            echo "Gcno files:"
            find . -name "*.gcno" -type f
            exit 1
          }
        fi

        # Show all coverage before filtering
        echo "=== Coverage summary for ${{ inputs.binary }} (all files) ==="
        lcov --summary ${{ inputs.binary }}-all.info

        # Filter to include only specified pattern
        echo "Filtering to include only ${{ inputs.coverage-include-pattern }} directory..."
        lcov --extract ${{ inputs.binary }}-all.info "*/${{ inputs.coverage-include-pattern }}/*" --output-file ${{ inputs.binary }}-filtered.info || {
          echo "Warning: No files matched pattern */${{ inputs.coverage-include-pattern }}/*"
          echo "Available files in coverage data:"
          lcov --list ${{ inputs.binary }}-all.info | head -20
          # Create empty info file to continue workflow
          echo "TN:" > ${{ inputs.binary }}-filtered.info
          echo "end_of_record" >> ${{ inputs.binary }}-filtered.info
        }

        # Show coverage summary
        echo "=== Coverage summary for ${{ inputs.binary }} (filtered) ==="
        lcov --summary ${{ inputs.binary }}-filtered.info

    - name: Upload coverage data
      uses: actions/upload-artifact@v5
      with:
        name: coverage-data-${{ inputs.binary }}
        path: test-${{ inputs.binary }}/${{ inputs.binary }}-filtered.info
        retention-days: 1

    - name: Set outputs
      id: set-outputs
      shell: bash
      run: |
        echo "coverage-file=${{ inputs.binary }}-filtered.info" >> $GITHUB_OUTPUT
        echo "artifact-name=coverage-data-${{ inputs.binary }}" >> $GITHUB_OUTPUT
