set(CMAKE_AR                        llvm-ar-14 CACHE FILEPATH "")
set(CMAKE_ASM_COMPILER              clang-14 CACHE FILEPATH "")
set(CMAKE_C_COMPILER                clang-14 CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER              clang++-14 CACHE FILEPATH "")
set(CMAKE_LINKER                    lld-14 CACHE FILEPATH "")
set(CMAKE_OBJCOPY                   llvm-objcopy-14 CACHE FILEPATH "")
set(CMAKE_RANLIB                    llvm-ranlib-14 CACHE FILEPATH "")
set(CMAKE_SIZE                      llvm-size-14 CACHE FILEPATH "")
set(CMAKE_STRIP                     llvm-strip-14 CACHE FILEPATH "")
set(CMAKE_GCOV                      llvm-cov-14 CACHE FILEPATH "")

set(PLATFORM_C_FLAGS                "" CACHE INTERNAL "")
set(PLATFORM_CXX_FLAGS              "${PLATFORM_C_FLAGS}" CACHE INTERNAL "")
set(CMAKE_C_FLAGS                   "${PLATFORM_C_FLAGS}" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS                 "${PLATFORM_CXX_FLAGS}" CACHE INTERNAL "")

set(CMAKE_C_FLAGS_DEBUG             "-O0 -g" CACHE INTERNAL "")
set(CMAKE_C_FLAGS_RELEASE           "-O3 -DNDEBUG" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_DEBUG           "${CMAKE_C_FLAGS_DEBUG}" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_RELEASE         "${CMAKE_C_FLAGS_RELEASE}" CACHE INTERNAL "")

set(PLATFORM_EXE_LINKER_FLAGS       "" CACHE INTERNAL "")
set(CMAKE_EXE_LINKER_FLAGS          "${PLATFORM_EXE_LINKER_FLAGS}" CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

include(${CMAKE_CURRENT_LIST_DIR}/../sanitizers.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../coverage.cmake)
