name: Build CMake preset with coverage
description: Build CMake preset with coverage

inputs:
  preset:
    description: CMake preset to build
    required: true

  cmakeExtraArgs:
    description: Extra arguments to pass to CMake (appended after -DWITH_COVERAGE=ON)
    required: false

  artifactBindir:
    description: Path to the binary output directory (relative to build directory)
    required: false
    default: bin

  artifactSuffix:
    description: Suffix appended to the artifact name
    required: false

outputs:
  coverage-artifact-name:
    description: Name of the uploaded coverage artifact
    value: ${{ steps.set-output.outputs.coverage-artifact-name }}

runs:
  using: composite
  steps:
    - uses: kubasejdak-org/cmake-build-preset-action@main
      with:
        preset: ${{ inputs.preset }}
        cmakeExtraArgs: '-DWITH_COVERAGE=ON ${{ inputs.cmakeExtraArgs }}'

    - name: Collect coverage artifacts
      shell: bash
      run: |
        # Create structured artifact directory for coverage processing
        mkdir -p coverage-artifacts/bin
        mkdir -p coverage-artifacts/gcno

        # Copy binaries
        echo "Collecting binaries from build/${{ inputs.artifactBindir }}/..."
        cp build/${{ inputs.artifactBindir }}/* coverage-artifacts/bin/

        # Copy gcno files preserving FULL directory structure including "build/" prefix
        # This is critical: gcov requires exact path matching between gcno and gcda files
        echo "Collecting gcno files with directory structure..."
        find build -name "*.gcno" -type f | while read gcno_file; do
          mkdir -p "coverage-artifacts/gcno/$(dirname "$gcno_file")"
          cp "$gcno_file" "coverage-artifacts/gcno/$gcno_file"
        done

        # Debug output for troubleshooting
        echo "=== Coverage artifacts structure ==="
        echo "Binaries: $(ls coverage-artifacts/bin/ | wc -l) files"
        echo "gcno files: $(find coverage-artifacts/gcno -name "*.gcno" | wc -l) files"
        echo "Sample structure:"
        find coverage-artifacts -type f

    - name: Set coverage artifact name
      id: set-output
      shell: bash
      run: echo "coverage-artifact-name=coverage-build-${{ inputs.preset }}${{ inputs.artifactSuffix }}" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v6
      with:
        name: ${{ steps.set-output.outputs.coverage-artifact-name }}
        path: coverage-artifacts/
