name: Run clang-format
description: Run clang-format

inputs:
  launchScriptPath:
    description: Path to script that launches clang-format
    required: false
    default: tools/check-clang-format.sh

runs:
  using: composite
  steps:
    - name: fix git permissions
      shell: bash
      run: git config --system --add safe.directory '*'
    - name: run clang-format
      shell: bash
      run: ${{ inputs.launchScriptPath }}
    - name: check for errors
      shell: bash
      run: |
        git diff --color > clang-format.patch
        if [[ `wc -l < clang-format.patch` != "0" ]]; then
          cat clang-format.patch
          git checkout -- .
          false
        fi
