name: Run clang-format
description: Run clang-format

inputs:
  launchScriptPath:
    description: Path to script that launches clang-format
    required: false
    default: tools/check-clang-format.sh

runs:
  using: composite
  steps:
    - name: run clang-format
      shell: bash
      run: |
        whoami
        pwd
        ls -al
        ${{ inputs.launchScriptPath }}
        echo "==============================================="
        git status
        echo "==============================================="

        git diff --color > clang-format.patch
        if [[ `wc -l < clang-format.patch` != "0" ]]; then
          cat clang-format.patch
          git checkout -- .
          false
        fi
