name: Run clang-tidy
description: Run clang-tidy

inputs:
  preset:
    description: CMake preset to use
    required: true

runs:
  using: composite
  steps:
    - name: Print Hello World
      shell: bash
      run: |
        echo "Hello World"
