name: Build with coverage instrumentation
description: Builds CMake preset with coverage enabled and collects artifacts for coverage processing

inputs:
  preset:
    description: CMake preset to build
    required: true
  cmakeExtraArgs:
    description: Additional CMake arguments (appended after -DWITH_COVERAGE=ON)
    required: false
    default: ''
  artifact-name:
    description: Name for the uploaded coverage artifacts
    required: false
    default: coverage-build-artifacts
  artifact-retention-days:
    description: Number of days to retain the coverage artifacts
    required: false
    default: '1'

outputs:
  artifact-name:
    description: Name of the uploaded artifact
    value: ${{ steps.set-output.outputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: Build with coverage instrumentation
      uses: kubasejdak-org/cmake-build-preset-action@main
      with:
        preset: ${{ inputs.preset }}
        cmakeExtraArgs: '-DWITH_COVERAGE=ON ${{ inputs.cmakeExtraArgs }}'

    - name: Collect coverage artifacts
      shell: bash
      run: |
        # Create structured artifact directory for coverage processing
        mkdir -p coverage-artifacts/bin
        mkdir -p coverage-artifacts/gcno-files

        # Copy binaries
        echo "Collecting binaries from build/bin/..."
        cp build/bin/* coverage-artifacts/bin/

        # Copy gcno files preserving FULL directory structure including "build/" prefix
        # This is critical: gcov requires exact path matching between gcno and gcda files
        # The embedded paths in gcno files include "build/" so we must preserve it
        echo "Collecting gcno files with directory structure..."
        find build -name "*.gcno" -type f | while read gcno_file; do
          # Preserve full path including "build/" directory
          mkdir -p "coverage-artifacts/gcno-files/$(dirname "$gcno_file")"
          cp "$gcno_file" "coverage-artifacts/gcno-files/$gcno_file"
        done

        # Debug output for troubleshooting
        echo "=== Coverage artifacts structure ==="
        echo "Binaries: $(ls coverage-artifacts/bin/ | wc -l) files"
        echo "gcno files: $(find coverage-artifacts/gcno-files -name "*.gcno" | wc -l) files"
        echo "Sample structure:"
        find coverage-artifacts -type f | head -20

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.artifact-name }}
        path: coverage-artifacts/
        retention-days: ${{ inputs.artifact-retention-days }}

    - name: Set output
      id: set-output
      shell: bash
      run: |
        echo "artifact-name=${{ inputs.artifact-name }}" >> $GITHUB_OUTPUT
